on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'python/**'

name: Python Validation
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python compile-validate
        working-directory: python
        run: |
          for i in *.py; do
            python -m py_compile $i
          done